const d = 10;
    try{
        d = 79;
    }catch (err){
        console.log(err);
    }

console.log(d);